name: Manual Email Dispatcher

on:
  workflow_dispatch:

jobs:
  send-notion-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip uninstall -y notion notion-client || true
          python -m pip install notion-client==2.7.0 jinja2

      - name: Run Notion Email Dispatcher
        env:
          NOTION_TOKEN: ${{ secrets.AUTO_DISPATCHER }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python send_emails.py
